plugins {
    id "com.android.library"
    id "org.jetbrains.kotlin.android"
}

group = "dev.jerson.openpgp"
version = "1.0-SNAPSHOT"

android {
    if (project.android.hasProperty("namespace")) {
        namespace = "dev.jerson.openpgp"
    }

    compileSdk = 35

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = "11"
    }

    sourceSets {
        main {
            java.srcDirs += "src/main/kotlin"
            jniLibs.srcDirs = ['src/main/jniLibs']
        }
        test {
            java.srcDirs += "src/test/kotlin"
        }
    }

    defaultConfig {
        minSdk = 21
    }

    dependencies {
        testImplementation("org.jetbrains.kotlin:kotlin-test")
        testImplementation("org.mockito:mockito-core:5.0.0")
    }

    testOptions {
        unitTests.all {
            useJUnitPlatform()

            testLogging {
               events "passed", "skipped", "failed", "standardOut", "standardError"
               outputs.upToDateWhen {false}
               showStandardStreams = true
            }
        }
    }
}
