
// Objective-C API for talking to the following Go packages
//
//	github.com/jerson/openpgp-mobile/openpgp
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Openpgp_FRAMEWORK_H__
#define __Openpgp_FRAMEWORK_H__

#include "Openpgp.objc.h"
#include "Universe.objc.h"

#endif
