// Objective-C API for talking to github.com/jerson/openpgp-mobile/bridge Go package.
//   gobind -lang=objc github.com/jerson/openpgp-mobile/bridge
//
// File is generated by gobind. Do not edit.

#ifndef __OpenPGPBridge_H__
#define __OpenPGPBridge_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * Call ...
 */
FOUNDATION_EXPORT NSData* _Nullable OpenPGPBridgeCall(NSString* _Nullable name, NSData* _Nullable payload, NSError* _Nullable* _Nullable error);

#endif
