
// Objective-C API for talking to the following Go packages
//
//	github.com/jerson/openpgp-mobile/bridge
//
// File is generated by gomobile bind. Do not edit.
#ifndef __OpenPGPBridge_FRAMEWORK_H__
#define __OpenPGPBridge_FRAMEWORK_H__

#include "OpenPGPBridge.objc.h"
#include "Universe.objc.h"

#endif
