name: Integration Tests Browser

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - 'v*'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@main
        with:
          flutter-version: '3.x'
          channel: 'stable'
      - name: install deps
        run: flutter pub get
      - name: Build web
        run: |
          cd example
          flutter config --enable-web
          flutter build web
          echo 'Web build succeeded'